"""screens/spell_card.py — Single spell card.

A           → goto details
B           → goto start
LEFT/RIGHT  → roll a new random spell (with curtain)
SHAKE       → roll a new random spell (with curtain)

Standalone:
    python3 pico-ui-kit/simulator/run.py screens/spell_card.py
"""

import sys

try:
    import os as _os
    _here = _os.path.dirname(_os.path.abspath(__file__))
    _root = _os.path.dirname(_here)
    _ui   = _os.path.join(_root, "pico-ui-kit")
    _lib  = _os.path.join(_root, "lib")
    for _p in (_root, _ui, _lib):
        if _p not in sys.path:
            sys.path.insert(0, _p)
except (AttributeError, NameError):
    pass

import random

import fonts.monob16 as _bold16
import fonts.monor8  as _reg8

from components.badge import badge
from components.button import button
import icons.option_a as _option_a_icon
import icons.sparkles as _ritual_icon

from drawing.line import dot
from drawing.rect import fill_rect
from drawing.text import text_w, word_wrap

from tokens.semantic import (
    STRUCTURE_SURFACES_LEVEL_0,
    STRUCTURE_BORDERS_LEVEL_3,
    STRUCTURE_BORDERS_LEVEL_4,
    TEXT_COLOUR_PRIMARY,
    TEXT_COLOUR_SECONDARY,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_001,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_002,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_003,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_004,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_005,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_006,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_007,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_009,
    COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BACKGROUND_NEUTRAL,
)
from tokens.viewport import GAP_2, GAP_3, GAP_4, PADDING_2

from data import spells as _spells_data

# ── Spell tuple field indices ────────────────────────────────────────────────
# Matches data/spells.py — regenerated by tools/build_spells.py.

(_NAME, _LEVEL, _RITUAL, _V, _S, _M,
 _CASTING_TIME, _USE, _PAGE, _CLASSES, _SCHOOL, _DESCRIPTION) = range(12)

# ── School → accent + stud colour ────────────────────────────────────────────

_SCHOOL_ACCENT = {
    'Evocation':     '001',
    'Conjuration':   '002',
    'Enchantment':   '003',
    'Illusion':      '004',
    'Divination':    '005',
    'Abjuration':    '006',
    'Necromancy':    '007',
    'Transmutation': '009',
}

_SCHOOL_BAR_COLOUR = {
    'Evocation':     COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_001,
    'Conjuration':   COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_002,
    'Enchantment':   COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_003,
    'Illusion':      COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_004,
    'Divination':    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_005,
    'Abjuration':    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_006,
    'Necromancy':    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_007,
    'Transmutation': COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_009,
}

_BAR_FALLBACK = COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BACKGROUND_NEUTRAL


def _accent(spell):
    return _SCHOOL_ACCENT.get(spell[_SCHOOL], 'neutral')


def _accent_bar_color(spell):
    return _SCHOOL_BAR_COLOUR.get(spell[_SCHOOL], _BAR_FALLBACK)


# ── Colour aliases ────────────────────────────────────────────────────────────

_BG        = STRUCTURE_SURFACES_LEVEL_0
_TEXT_PRI  = TEXT_COLOUR_PRIMARY
_TEXT_SEC  = TEXT_COLOUR_SECONDARY
_SEPARATOR = STRUCTURE_BORDERS_LEVEL_3
_ICON_PH   = STRUCTURE_BORDERS_LEVEL_4

# ── Layout constants (240×135) ───────────────────────────────────────────────

_PAD     = GAP_4              # 12
_ICON_BOX = 36                # Figma "Schools" container — icon renders at natural size inside
_BAR_W   = 40
_BAR_H   = 2
_BADGE_H = _reg8.height() + PADDING_2 * 2  # 14
_BTN_H   = _reg8.height() + 8 + 2          # button height with focus space

_TEXT_X  = _PAD + _ICON_BOX + GAP_3

_ROW1_Y  = _PAD
_ROW3_Y  = 135 - _PAD - _BTN_H
_ROW2_Y  = (_ROW1_Y + _BADGE_H + _ROW3_Y - _ICON_BOX) // 2  # vertically centred

# ── State ─────────────────────────────────────────────────────────────────────

_idx = -1
_current_spell = None


# ── Public surface ───────────────────────────────────────────────────────────

def draw(display):
    global _idx, _current_spell
    if _idx < 0:
        _idx = random.randint(0, _spells_data.count() - 1)
        _current_spell = _spells_data.get(_idx)
    elif _current_spell is None:
        _current_spell = _spells_data.get(_idx)
    _render(display, _current_spell)


def on_input(key, display):
    global _idx, _current_spell
    if key in ('LEFT', 'RIGHT', 'SHAKE'):
        new = random.randint(0, _spells_data.count() - 2)
        _idx = new if new < _idx else new + 1
        _current_spell = _spells_data.get(_idx)
        from screens import transitions
        transitions.curtain(display, draw)
        return
    if key == 'A':
        from screens import router
        router.goto('details', display)
        return
    if key == 'B':
        from screens import router
        router.goto('start', display)
        return


def current_index():
    return _idx


def current_spell():
    return _current_spell


# ── Renderer ──────────────────────────────────────────────────────────────────

def _render(display, spell):
    display.fill(_BG)
    _draw_top_row(display, spell, _reg8)
    _draw_middle_row(display, spell, _bold16, _reg8)
    _draw_bottom_row(display, spell, _reg8)
    display.show()


def _draw_top_row(display, spell, font):
    x = _PAD
    acc = _accent(spell)

    level = str(spell[_LEVEL])
    x += badge(display, font, level, x, _ROW1_Y,
               colour=acc, emphasis='subtle', status_dot=False, icon=False)

    if spell[_RITUAL]:
        x += GAP_3
        badge(display, font, '', x, _ROW1_Y,
              colour=acc, emphasis='subtle', status_dot=False, icon=_ritual_icon)

    components = []
    if spell[_V]: components.append('V')
    if spell[_S]: components.append('S')
    if spell[_M]: components.append('M')
    _draw_components_right(display, font, components, _ROW1_Y)


def _draw_middle_row(display, spell, font_bold, font_reg):
    _draw_school_icon(display, spell[_SCHOOL], _PAD, _ROW2_Y)

    name = spell[_NAME]
    chars_per_line = (240 - _TEXT_X - _PAD) // font_bold.max_width()
    lines = word_wrap(name, chars_per_line) or [name]
    name_h = font_bold.height() * len(lines)

    total_h = name_h + GAP_2 + _BAR_H + GAP_2 + font_reg.height()
    name_y  = _ROW2_Y + (_ICON_BOX - total_h) // 2

    for i, line in enumerate(lines):
        display.write(font_bold, line, _TEXT_X, name_y + i * font_bold.height(),
                      _TEXT_PRI, None)

    fill_rect(display, _TEXT_X, name_y + name_h + GAP_2, _BAR_W, _BAR_H,
              _accent_bar_color(spell))

    meta_top = name_y + name_h + GAP_2 + _BAR_H + GAP_2
    _draw_meta(display, font_reg, spell, _TEXT_X, meta_top)


def _draw_meta(display, font, spell, x, y):
    casting = spell[_CASTING_TIME]
    use     = spell[_USE]

    display.write(font, casting, x, y, _TEXT_SEC, None)
    x += text_w(font, casting) + GAP_2
    dot(display, x, y + (font.height() - 2) // 2, _SEPARATOR)
    x += 2 + GAP_2
    display.write(font, use, x, y, _TEXT_SEC, None)


def _draw_bottom_row(display, spell, font):
    button(display, font, 'details', _PAD, _ROW3_Y,
           type='primary', trail_icon=_option_a_icon)

    page_str = 'p.' + str(spell[_PAGE])
    page_w = text_w(font, page_str) + PADDING_2 * 2
    page_y = _ROW3_Y + (_BTN_H - _BADGE_H) // 2
    badge(display, font, page_str, 240 - _PAD - page_w, page_y,
          colour='neutral', emphasis='ghost', type='semantic',
          status_dot=False, icon=False)


def _draw_components_right(display, font, labels, y):
    if not labels:
        return
    widths = [text_w(font, l) + PADDING_2 * 2 for l in labels]
    sep_w  = GAP_2 + 2 + GAP_2
    total  = sum(widths) + (len(labels) - 1) * sep_w
    x = 240 - _PAD - total
    for i, (label, w) in enumerate(zip(labels, widths)):
        if i > 0:
            x += GAP_2
            dot(display, x, y + (_BADGE_H - 2) // 2, _SEPARATOR)
            x += 2 + GAP_2
        badge(display, font, label, x, y,
              colour='neutral', emphasis='ghost', type='semantic',
              status_dot=False, icon=False)
        x += w


def _draw_school_icon(display, school, sx, sy):
    """Render the school's 1-bit bitmap centred in the _ICON_BOX area
    using the colour sampled from the source PNG."""
    try:
        from school_icons import ICONS
        entry = ICONS.get(school)
    except ImportError:
        entry = None

    if entry is None:
        return

    w, h, bitmap, colour = entry
    ix = sx + (_ICON_BOX - w) // 2
    iy = sy + (_ICON_BOX - h) // 2
    row_bytes = (w + 7) // 8
    blen = len(bitmap)
    for row in range(h):
        py = iy + row
        row_off = row * row_bytes
        for col in range(w):
            b = row_off + (col >> 3)
            if b < blen and bitmap[b] & (1 << (7 - (col & 7))):
                display.pixel(ix + col, py, colour)
