#!/usr/bin/env python3
"""
tools/build_icons.py

Converts school icon PNGs in data/src/icons/ to a 1-bit bitmap module
and writes lib/school_icons.py.

Usage:
    python3 tools/build_icons.py

Requirements:
    pip install pillow

Source PNGs:
    data/src/icons/<School>.png  (e.g. Evocation.png)
    Export from Figma at 36px or larger with transparency.
"""

import os
from PIL import Image

_HERE   = os.path.dirname(os.path.abspath(__file__))
SRC_DIR = os.path.join(_HERE, '..', 'data', 'src', 'icons')
DST     = os.path.join(_HERE, '..', 'lib', 'school_icons.py')

TARGET = 36   # icons are scaled to fit within TARGET×TARGET px

SCHOOLS = [
    'Evocation',
    'Enchantment',
    'Illusion',
    'Divination',
    'Abjuration',
    'Conjuration',
    'Transmutation',
    'Necromancy',
]


def _dominant_colour(img):
    """Return the most common opaque RGB pixel in the image."""
    counts = {}
    w, h = img.size
    for y in range(h):
        for x in range(w):
            r, g, b, a = img.getpixel((x, y))
            if a > 200:
                key = (r, g, b)
                counts[key] = counts.get(key, 0) + 1
    if not counts:
        return (255, 255, 255)
    return max(counts.items(), key=lambda kv: kv[1])[0]


def _to_bitmap(path, target=TARGET):
    """Load PNG, sample dominant colour, scale to fit target×target,
    return (w, h, 1-bit bytes, (r, g, b))."""
    img = Image.open(path).convert('RGBA')
    colour = _dominant_colour(img)
    img.thumbnail((target, target), Image.LANCZOS)
    w, h = img.size

    row_bytes = (w + 7) // 8
    buf = bytearray(row_bytes * h)
    for row in range(h):
        for col in range(w):
            _, _, _, a = img.getpixel((col, row))
            if a > 64:
                idx = row * row_bytes + col // 8
                buf[idx] |= 1 << (7 - col % 8)
    return w, h, bytes(buf), colour


def build():
    entries = {}
    for school in SCHOOLS:
        path = os.path.join(SRC_DIR, f'{school}.png')
        if not os.path.exists(path):
            print(f'  SKIP {school} — {path} not found')
            continue
        print(f'  {school}...', end=' ', flush=True)
        w, h, bmp, colour = _to_bitmap(path)
        entries[school] = (w, h, bmp, colour)
        print(f'{w}×{h}px, {len(bmp)} bytes, rgb={colour}')

    with open(DST, 'w', encoding='utf-8') as f:
        f.write('# Auto-generated by tools/build_icons.py — do not edit.\n')
        f.write('# Source: data/src/icons/<School>.png\n')
        f.write('# Re-run after updating the PNGs.\n')
        f.write('# Format per entry: (width, height, bitmap, (r, g, b))\n')
        f.write('# Bitmap: 1-bit MSB-first, rows padded to byte boundary.\n')
        f.write('# Colour: dominant opaque pixel sampled from the source PNG.\n\n')
        f.write('ICONS = {\n')
        for school, (w, h, bmp, colour) in entries.items():
            f.write(f"    {school!r}: ({w}, {h}, {bmp!r}, {colour!r}),\n")
        f.write('}\n')

    print(f'Written -> {os.path.relpath(DST)}')


if __name__ == '__main__':
    build()
